# Generated by Django 4.2.17 on 2024-12-11 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='inoice_number',
            new_name='invoice_number',
        ),
    ]
