# Generated by Django 5.1.4 on 2024-12-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_client_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='name',
        ),
    ]
