# Generated by Django 5.1.4 on 2024-12-11 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_client_remove_item_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedmodel',
            name='date_issued',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 12, 11)),
            preserve_default=False,
        ),
    ]
