# Generated by Django 5.1.4 on 2024-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_unifiedmodel_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
